In [10]:
from keras.models import Model
from keras.layers import Input, Dense, LSTM
from keras.optimizers import Adadelta

import numpy as np

inp = Input(shape=(None, 3))

f = LSTM(5, return_sequences=True)(inp)
b = LSTM(5, return_sequences=True, go_backwards=True)(inp)

mf = Model(inputs=(inp,), outputs=(f,))
mb = Model(inputs=(inp,), outputs=(b,))

#mb.compile(loss='mean_squared_error', optimizer=Adadelta())
#mf.compile(loss='mean_squared_error', optimizer=Adadelta())


mf.set_weights(mb.get_weights())

x = np.random.random((1,5,3))

print mf.predict(x)
print mb.predict(x[:, ::-1, :])

[[[ 0.02677396 -0.01570731  0.1488453   0.02892883  0.08291504]
  [ 0.11539099  0.01385299  0.21863274 -0.01548169  0.11000045]
  [ 0.15411161  0.01749671  0.30971262 -0.02676236  0.10856816]
  [ 0.20070231  0.02405731  0.32748985 -0.03598929  0.13359897]
  [ 0.18734573  0.03043482  0.36210623 -0.04483346  0.06785216]]]
[[[ 0.02677396 -0.01570731  0.1488453   0.02892883  0.08291504]
  [ 0.11539099  0.01385299  0.21863274 -0.01548169  0.11000045]
  [ 0.15411161  0.01749671  0.30971262 -0.02676236  0.10856816]
  [ 0.20070231  0.02405731  0.32748985 -0.03598929  0.13359897]
  [ 0.18734573  0.03043482  0.36210623 -0.04483346  0.06785216]]]
